services:
  jekyll:
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    # network_mode: host
    # command: jekyll serve --livereload
    command: jekyll serve --host 0.0.0.0 --livereload